#include "STD_TYPES.h"
#include "BIT_MATH.h"
#include "MRCC_interface.h"
#include "SYSTICK_int.h"
#include "GPIO_interface.h"
#include "SPI_interface.h"
#include "TFT_interface.h"
#include "STP_interface.h"
#define x 100


//000000000000
#include "NVIC_INTERFACE.h"

#include "R2RDAC_INTERFACE.h"
#include "STP_interface.h"
#include "song.h"
//000000000000


#include "img.h"


int main (void)
{
	MRCC_vInt();
	MRCC_vEnable(RCC_AHB1,AHB1_GPIOA);
	MRCC_vEnable(RCC_AHB1,AHB1_GPIOB);//00000000
	MRCC_vEnable(RCC_APB2,APB2_SPI1);
	SYSTICK_voidInit();
	SYSTICK_voidEnable();
	R2RDAC_Init();
	S2P_vInit();
	MGPIO_vSetMode(PORT_A,PIN_0,MODE_OUTPUT);
	MGPIO_vSetMode(PORT_A,PIN_1,MODE_OUTPUT);
	MGPIO_vSetOutputMode(PORT_A,PIN_0,OUTPUT_PUSHPULL,SPEED_LOW);
	MGPIO_vSetOutputMode(PORT_A,PIN_1,OUTPUT_PUSHPULL,SPEED_LOW);

	MGPIO_vSetMode(PORT_A,PIN_4,MODE_ALTERNATIVE);
	MGPIO_vSetMode(PORT_A,PIN_5,MODE_ALTERNATIVE);
	MGPIO_vSetMode(PORT_A,PIN_6,MODE_ALTERNATIVE);
	MGPIO_vSetMode(PORT_A,PIN_7,MODE_ALTERNATIVE);
	MGPIO_vSetAlternativeMode(PORT_A,PIN_4,ALTR_SPI);
	MGPIO_vSetAlternativeMode(PORT_A,PIN_5,ALTR_SPI);
	MGPIO_vSetAlternativeMode(PORT_A,PIN_6,ALTR_SPI);
	MGPIO_vSetAlternativeMode(PORT_A,PIN_7,ALTR_SPI);

	SPI1_voidInit();
	//SPI1_u16Transceive(1);
	HTFT_voidInit();
	//SPI1_u16Transceive(1);
	HTFT_voidDisplayImage(img);




	while (1)
	{
		R2RDAC_SetData(song_raw,37731);


		S2P_vSendData(0xFEF8);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFD24);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFB22);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xF722);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xEF24);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xDFF8);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF00);
					SYSTICK_voidDelayUs(10);
					SYSTICK_voidDelayMs(x);
					//****
					S2P_vSendData(0xFE24);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFD22);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFB22);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xF724);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xEFF8);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xDF00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBFFC);
					SYSTICK_voidDelayUs(10);
					SYSTICK_voidDelayMs(x);
					//*********
					S2P_vSendData(0xFE22);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFD22);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFB24);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xF7F8);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xEF00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xDF00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBFFC);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF04);
					SYSTICK_voidDelayUs(10);
					SYSTICK_voidDelayMs(x);
					//*************
					S2P_vSendData(0xFE22);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFD24);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFBF8);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xF700);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xEF00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xDFFC);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF04);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF08);
					SYSTICK_voidDelayUs(10);
					SYSTICK_voidDelayMs(x);
					//*************
					S2P_vSendData(0xFE24);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFDF8);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFB00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xF700);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xEFFC);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xDF04);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF08);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBFF0);
					SYSTICK_voidDelayUs(10);
					SYSTICK_voidDelayMs(x);
					//***************
					S2P_vSendData(0xFEF8);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFD00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFB00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xF7FC);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xEF04);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xDF08);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBFF0);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF08);
					SYSTICK_voidDelayUs(10);
					SYSTICK_voidDelayMs(2500000);
			        //***************
					S2P_vSendData(0xFE00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFD00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFBFC);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xF704);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xEF08);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xDFF0);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF08);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF04);
					SYSTICK_voidDelayUs(10);
					SYSTICK_voidDelayMs(x);
					//****************
					S2P_vSendData(0xFE00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFDFC);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFB04);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xF708);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xEFF0);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xDF08);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF04);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBFFC);
					SYSTICK_voidDelayUs(10);
					SYSTICK_voidDelayMs(x);
					//**************
					S2P_vSendData(0xFEFC);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFD04);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFB08);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xF7F0);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xEF08);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xDF04);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBFFC);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF00);
					SYSTICK_voidDelayUs(10);
					SYSTICK_voidDelayMs(x);
					//***************
					S2P_vSendData(0xFE04);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFD08);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFBF0);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xF708);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xEF04);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xDFFC);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBFFC);
					SYSTICK_voidDelayUs(10);
					SYSTICK_voidDelayMs(x);
			        //***************
					S2P_vSendData(0xFE08);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFDF0);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFB08);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xF704);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xEFFC);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xDF00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBFFC);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF24);
					SYSTICK_voidDelayUs(10);
					SYSTICK_voidDelayMs(x);
					//**************
					S2P_vSendData(0xFEF0);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFD08);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFB04);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xF7FC);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xEF00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xDFFC);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF24);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF24);
					SYSTICK_voidDelayUs(10);
					SYSTICK_voidDelayMs(2500000);
					//************
					S2P_vSendData(0xFE08);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFD04);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFBFC);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xF700);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xEFFC);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xDF24);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF24);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF58);
					SYSTICK_voidDelayUs(10);
					SYSTICK_voidDelayMs(x);
					//**********
					S2P_vSendData(0xFE04);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFDFC);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFB00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xF7FC);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xEF24);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xDF24);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF58);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF80);
					SYSTICK_voidDelayUs(10);
					SYSTICK_voidDelayMs(x);
					//***********
					S2P_vSendData(0xFEFC);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFD00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFBFC);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xF724);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xEF24);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xDF58);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF80);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF00);
					SYSTICK_voidDelayUs(10);
					SYSTICK_voidDelayMs(x);
					//**********
					S2P_vSendData(0xFE00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFDFC);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFB24);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xF724);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xEF58);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xDF80);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBFFC);
					SYSTICK_voidDelayUs(10);
					SYSTICK_voidDelayMs(x);
					//***********
					S2P_vSendData(0xFEFC);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFD24);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFB24);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xF758);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xEF80);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xDF00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBFFC);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF54);
					SYSTICK_voidDelayUs(10);
					SYSTICK_voidDelayMs(x);
					//***********
					S2P_vSendData(0xFE24);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFD24);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFB58);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xF780);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xEF00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xDFFC);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF84);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF48);
					SYSTICK_voidDelayUs(10);
					SYSTICK_voidDelayMs(x);
					//**********
					S2P_vSendData(0xFE24);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFD58);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFB80);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xF700);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xEFFC);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xDF84);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF48);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF30);
					SYSTICK_voidDelayUs(10);
					SYSTICK_voidDelayMs(2500000);
					//***********
					S2P_vSendData(0xFE58);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFD80);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFB00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xF7FC);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xEF84);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xDF48);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF30);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF00);

					SYSTICK_voidDelayUs(10);
					SYSTICK_voidDelayMs(x);
					//************
					S2P_vSendData(0xFE80);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFD00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFBFC);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xF784);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xEF48);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xDF30);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBFF4);

					SYSTICK_voidDelayUs(10);
					SYSTICK_voidDelayMs(x);
					//**********
					S2P_vSendData(0xFE00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFDFC);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFB84);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xF748);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xEF30);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xDF00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBFF4);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF00);
					SYSTICK_voidDelayUs(10);
					SYSTICK_voidDelayMs(x);
					//**********
					S2P_vSendData(0xFEFC);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFD84);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFB48);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xF730);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xEF00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xDFF4);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBFF0);
					SYSTICK_voidDelayUs(10);
					SYSTICK_voidDelayMs(x);
					//**********
					S2P_vSendData(0xFE84);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFD48);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFB30);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xF700);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xEFF4);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xDF00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBFF0);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF28);
					SYSTICK_voidDelayUs(10);
					SYSTICK_voidDelayMs(x);
					//***********
					S2P_vSendData(0xFE48);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFD30);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFB00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xF7F4);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xEF00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xDFF0);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF28);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF24);
					SYSTICK_voidDelayUs(10);
					SYSTICK_voidDelayMs(x);
					//**********
					S2P_vSendData(0xFE30);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFD00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFBF4);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xF700);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xEFF0);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xDF28);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF24);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF28);
					SYSTICK_voidDelayUs(10);
					SYSTICK_voidDelayMs(x);
					//***********
					S2P_vSendData(0xFE00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFDF4);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFB00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xF7F0);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xEF28);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xDF24);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF28);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBFF0);
					SYSTICK_voidDelayUs(10);
					SYSTICK_voidDelayMs(x);
					//***********
					S2P_vSendData(0xFEF4);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFD00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFBF0);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xF728);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xEF24);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xDF28);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBFF0);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF00);
					SYSTICK_voidDelayUs(10);
					SYSTICK_voidDelayMs(x);
					//***********
					S2P_vSendData(0xFE00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFDF0);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFB28);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xF724);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xEF28);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xDFF0);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBFFC);
					SYSTICK_voidDelayUs(10);
					SYSTICK_voidDelayMs(x);
					//**********
					S2P_vSendData(0xFEF0);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFD28);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFB24);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xF728);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xEFF0);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xDF00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBFFC);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF90);
					SYSTICK_voidDelayUs(10);
					SYSTICK_voidDelayMs(x);
					//**********
					S2P_vSendData(0xFE28);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFD24);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xFB28);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xF7F0);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xEF00);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xDFFC);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBF90);
					SYSTICK_voidDelayUs(10);
					S2P_vSendData(0xBFF0);
					SYSTICK_voidDelayUs(10);
					SYSTICK_voidDelayMs(x);






	}

}
